# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fire.FCCS <- function(FCCSpropsSI, MliveSI = as.numeric( c(90, 90, 60)), MdeadSI = as.numeric( c(6, 6, 6, 6, 6)), slope = 0.0, windSpeedSI = 11.0) {
    .Call('medfate_FCCSbehaviour', PACKAGE = 'medfate', FCCSpropsSI, MliveSI, MdeadSI, slope, windSpeedSI)
}

fire.Rothermel <- function(modeltype, wSI, sSI, delta, mx_dead, hSI, mSI, u, windDir, slope, aspect) {
    .Call('medfate_rothermel', PACKAGE = 'medfate', modeltype, wSI, sSI, delta, mx_dead, hSI, mSI, u, windDir, slope, aspect)
}

.genros <- function(phi, theta, a1, a2, b, n1, n2, c) {
    .Call('medfate_genros', PACKAGE = 'medfate', phi, theta, a1, a2, b, n1, n2, c)
}

.ellipseROS <- function(phi, theta, vws, ros) {
    .Call('medfate_ellipseROS', PACKAGE = 'medfate', phi, theta, vws, ros)
}

.doubleEllipseROS <- function(phi, theta, vws, ros) {
    .Call('medfate_doubleEllipseROS', PACKAGE = 'medfate', phi, theta, vws, ros)
}

.fireBrandFallingHeight <- function(initialHeight, timeFalling, Dp) {
    .Call('medfate_fireBrandFallingHeight', PACKAGE = 'medfate', initialHeight, timeFalling, Dp)
}

.totalFirebrandLoftingTime <- function(z, z0, zF, Dp) {
    .Call('medfate_totalFirebrandLoftingTime', PACKAGE = 'medfate', z, z0, zF, Dp)
}

.totalGasFlowPersistenceTime <- function(z, t0, zF) {
    .Call('medfate_totalGasFlowPersistenceTime', PACKAGE = 'medfate', z, t0, zF)
}

.findFireBrandLoftedHeight <- function(t0, z0, zF, Dp) {
    .Call('medfate_findFireBrandLoftedHeight', PACKAGE = 'medfate', t0, z0, zF, Dp)
}

.willBurnWhenHitFloor <- function(zIni, Dp) {
    .Call('medfate_willBurnWhenHitFloor', PACKAGE = 'medfate', zIni, Dp)
}

.fireBrandBurningTimeFromCanopyStructure <- function(LAIc) {
    .Call('medfate_fireBrandBurningTimeFromCanopyStructure', PACKAGE = 'medfate', LAIc)
}

.fireBrandFlameHeightFromCanopyStructure <- function(crownLength, LAIc) {
    .Call('medfate_fireBrandFlameHeightFromCanopyStructure', PACKAGE = 'medfate', crownLength, LAIc)
}

.criticalFirelineIntensity <- function(CBH, M) {
    .Call('medfate_criticalFirelineIntensity', PACKAGE = 'medfate', CBH, M)
}

.checkSpeciesParameters <- function(SpParams, params) {
    invisible(.Call('medfate_checkSpeciesParameters', PACKAGE = 'medfate', SpParams, params))
}

root.conicRS <- function(Z, d) {
    .Call('medfate_conicRS', PACKAGE = 'medfate', Z, d)
}

root.ldrRS <- function(Z50, Z95, d) {
    .Call('medfate_ldrRS', PACKAGE = 'medfate', Z50, Z95, d)
}

root.ldrProfile <- function(Z50, Z95, d) {
    .Call('medfate_ldrProfile', PACKAGE = 'medfate', Z50, Z95, d)
}

plant.Parameter <- function(x, SpParams, parName) {
    .Call('medfate_cohortParameter', PACKAGE = 'medfate', x, SpParams, parName)
}

plant.CharacterParameter <- function(x, SpParams, parName) {
    .Call('medfate_cohortCharacterParameter', PACKAGE = 'medfate', x, SpParams, parName)
}

plant.Species <- function(x) {
    .Call('medfate_cohortSpecies', PACKAGE = 'medfate', x)
}

plant.SpeciesName <- function(x, SpParams) {
    .Call('medfate_cohortSpeciesName', PACKAGE = 'medfate', x, SpParams)
}

.treeBasalArea <- function(N, dbh) {
    .Call('medfate_treeBasalArea', PACKAGE = 'medfate', N, dbh)
}

plant.BasalArea <- function(x) {
    .Call('medfate_cohortBasalArea', PACKAGE = 'medfate', x)
}

species.BasalArea <- function(x, SpParams) {
    .Call('medfate_speciesBasalArea', PACKAGE = 'medfate', x, SpParams)
}

plant.LargerTreeBasalArea <- function(x) {
    .Call('medfate_cohortLargerTreeBasalArea', PACKAGE = 'medfate', x)
}

forest.BasalArea <- function(x) {
    .Call('medfate_forestBasalArea', PACKAGE = 'medfate', x)
}

plant.Density <- function(x) {
    .Call('medfate_cohortDensity', PACKAGE = 'medfate', x)
}

plant.Height <- function(x) {
    .Call('medfate_cohortHeight', PACKAGE = 'medfate', x)
}

.shrubCrownRatio <- function(SP, SpParams) {
    .Call('medfate_shrubCrownRatio', PACKAGE = 'medfate', SP, SpParams)
}

plant.CrownRatio <- function(x, SpParams) {
    .Call('medfate_cohortCrownRatio', PACKAGE = 'medfate', x, SpParams)
}

plant.CrownBaseHeight <- function(x, SpParams) {
    .Call('medfate_cohortCrownBaseHeight', PACKAGE = 'medfate', x, SpParams)
}

plant.CrownLength <- function(x, SpParams) {
    .Call('medfate_cohortCrownLength', PACKAGE = 'medfate', x, SpParams)
}

.treeFoliarBiomass <- function(SP, N, dbh, SpParams, gdd = NA_real_) {
    .Call('medfate_treeFoliarBiomass', PACKAGE = 'medfate', SP, N, dbh, SpParams, gdd)
}

.shrubFoliarBiomass <- function(SP, Cover, H, CR, SpParams, gdd = NA_real_) {
    .Call('medfate_shrubFoliarBiomass', PACKAGE = 'medfate', SP, Cover, H, CR, SpParams, gdd)
}

plant.FoliarBiomass <- function(x, SpParams, gdd = NA_real_) {
    .Call('medfate_cohortFoliarBiomass', PACKAGE = 'medfate', x, SpParams, gdd)
}

.shrubCover <- function(x, excludeMinHeight = 0.0) {
    .Call('medfate_shrubCover', PACKAGE = 'medfate', x, excludeMinHeight)
}

plant.Cover <- function(x) {
    .Call('medfate_cohortCover', PACKAGE = 'medfate', x)
}

.shrubCrownPhytovolume <- function(SP, Cover, H, CR, SpParams) {
    .Call('medfate_shrubCrownPhytovolume', PACKAGE = 'medfate', SP, Cover, H, CR, SpParams)
}

plant.Phytovolume <- function(x, SpParams) {
    .Call('medfate_cohortPhytovolume', PACKAGE = 'medfate', x, SpParams)
}

.treeFuel <- function(SP, N, dbh, SpParams, gdd = NA_real_, includeDead = TRUE) {
    .Call('medfate_treeFuel', PACKAGE = 'medfate', SP, N, dbh, SpParams, gdd, includeDead)
}

.shrubFuel <- function(SP, Cover, H, CR, SpParams, gdd = NA_real_, includeDead = TRUE) {
    .Call('medfate_shrubFuel', PACKAGE = 'medfate', SP, Cover, H, CR, SpParams, gdd, includeDead)
}

plant.Fuel <- function(x, SpParams, gdd = NA_real_, includeDead = TRUE) {
    .Call('medfate_cohortFuel', PACKAGE = 'medfate', x, SpParams, gdd, includeDead)
}

plant.EquilibriumLeafLitter <- function(x, SpParams, AET = 800) {
    .Call('medfate_cohortEquilibriumLeafLitter', PACKAGE = 'medfate', x, SpParams, AET)
}

plant.EquilibriumSmallBranchLitter <- function(x, SpParams, smallBranchDecompositionRate = 0.81) {
    .Call('medfate_cohortEquilibriumSmallBranchLitter', PACKAGE = 'medfate', x, SpParams, smallBranchDecompositionRate)
}

.treeLAI <- function(SP, N, dbh, SpParams, gdd = NA_real_) {
    .Call('medfate_treeLAI', PACKAGE = 'medfate', SP, N, dbh, SpParams, gdd)
}

.shrubLAI <- function(SP, Cover, H, SpParams, gdd = NA_real_) {
    .Call('medfate_shrubLAI', PACKAGE = 'medfate', SP, Cover, H, SpParams, gdd)
}

plant.LAI <- function(x, SpParams, gdd = NA_real_) {
    .Call('medfate_cohortLAI', PACKAGE = 'medfate', x, SpParams, gdd)
}

.LAIdistribution <- function(z, x, SpParams, gdd = NA_real_) {
    .Call('medfate_LAIdistribution', PACKAGE = 'medfate', z, x, SpParams, gdd)
}

.LAIprofile <- function(z, x, SpParams, gdd = NA_real_) {
    .Call('medfate_LAIprofile', PACKAGE = 'medfate', z, x, SpParams, gdd)
}

swbInput <- function(SP, LAI, H, CR, V, SpParams, petMode = "Input", hydraulicMode = "Simple") {
    .Call('medfate_swbInput', PACKAGE = 'medfate', SP, LAI, H, CR, V, SpParams, petMode, hydraulicMode)
}

forest2swbInput <- function(x, SpParams, d, gdd = NA_real_, petMode = "Input", hydraulicMode = "Simple") {
    .Call('medfate_forest2swbInput', PACKAGE = 'medfate', x, SpParams, d, gdd, petMode, hydraulicMode)
}

.fuelConditions <- function(airTemp, airHumidity, fuelRadiation, fuelWindSpeed) {
    .Call('medfate_fuelConditions', PACKAGE = 'medfate', airTemp, airHumidity, fuelRadiation, fuelWindSpeed)
}

.EMCdesorption <- function(fuelTemperature, fuelHumidity) {
    .Call('medfate_EMCdesorption', PACKAGE = 'medfate', fuelTemperature, fuelHumidity)
}

.EMCadsorption <- function(fuelTemperature, fuelHumidity) {
    .Call('medfate_EMCadsorption', PACKAGE = 'medfate', fuelTemperature, fuelHumidity)
}

.EMCSimard <- function(fuelTemperature, fuelHumidity) {
    .Call('medfate_EMCSimard', PACKAGE = 'medfate', fuelTemperature, fuelHumidity)
}

.woodyFuelProfile <- function(z, x, SpParams, gdd = NA_real_) {
    .Call('medfate_woodyFuelProfile', PACKAGE = 'medfate', z, x, SpParams, gdd)
}

.layerCohortFuelLoading <- function(minHeight, maxHeight, cohortLoading, H, CR) {
    .Call('medfate_layerCohortFuelLoading', PACKAGE = 'medfate', minHeight, maxHeight, cohortLoading, H, CR)
}

.layerFuelLoading <- function(minHeight, maxHeight, cohortLoading, H, CR) {
    .Call('medfate_layerFuelLoading', PACKAGE = 'medfate', minHeight, maxHeight, cohortLoading, H, CR)
}

.layerLAI <- function(minHeight, maxHeight, cohortLAI, H, CR) {
    .Call('medfate_layerLAI', PACKAGE = 'medfate', minHeight, maxHeight, cohortLAI, H, CR)
}

.layerFuelAverageSpeciesParameter <- function(spParName, minHeight, maxHeight, x, SpParams, gdd = NA_real_) {
    .Call('medfate_layerFuelAverageSpeciesParameter', PACKAGE = 'medfate', spParName, minHeight, maxHeight, x, SpParams, gdd)
}

.layerFuelAverageParameter <- function(minHeight, maxHeight, cohortParameter, cohortLoading, H, CR) {
    .Call('medfate_layerFuelAverageParameter', PACKAGE = 'medfate', minHeight, maxHeight, cohortParameter, cohortLoading, H, CR)
}

.layerFuelAverageCrownLength <- function(minHeight, maxHeight, cohortCrownLength, cohortLoading, H, CR) {
    .Call('medfate_layerFuelAverageCrownLength', PACKAGE = 'medfate', minHeight, maxHeight, cohortCrownLength, cohortLoading, H, CR)
}

fuel.Stratification <- function(object, SpParams, gdd = NA_real_, heightProfileStep = 10.0, maxHeightProfile = 5000.0, bulkDensityThreshold = 0.05) {
    .Call('medfate_fuelLiveStratification', PACKAGE = 'medfate', object, SpParams, gdd, heightProfileStep, maxHeightProfile, bulkDensityThreshold)
}

fuel.FCCS <- function(object, ShrubCover, CanopyCover, SpParams, gdd = NA_real_, heightProfileStep = 10.0, maxHeightProfile = 5000, bulkDensityThreshold = 0.05) {
    .Call('medfate_FCCSproperties', PACKAGE = 'medfate', object, ShrubCover, CanopyCover, SpParams, gdd, heightProfileStep, maxHeightProfile, bulkDensityThreshold)
}

.gammds <- function(x, p) {
    .Call('medfate_gammds', PACKAGE = 'medfate', x, p)
}

.Egamma <- function(psi, kxmax, c, d) {
    .Call('medfate_Egamma', PACKAGE = 'medfate', psi, kxmax, c, d)
}

hydraulics.EXylem <- function(psiPlant, psiUpstream, kxmax, c, d) {
    .Call('medfate_EXylem', PACKAGE = 'medfate', psiPlant, psiUpstream, kxmax, c, d)
}

hydraulics.xylemConductance <- function(psi, kxmax, c, d) {
    .Call('medfate_xylemConductance', PACKAGE = 'medfate', psi, kxmax, c, d)
}

hydraulics.psiCrit <- function(c, d) {
    .Call('medfate_psiCrit', PACKAGE = 'medfate', c, d)
}

hydraulics.E2psiXylem <- function(E, psiUpstream, kxmax, c, d, psiStep = -0.01, psiMax = -10.0) {
    .Call('medfate_E2psiXylem', PACKAGE = 'medfate', E, psiUpstream, kxmax, c, d, psiStep, psiMax)
}

hydraulics.Ecrit <- function(psiUpstream, kxmax, c, d) {
    .Call('medfate_Ecrit', PACKAGE = 'medfate', psiUpstream, kxmax, c, d)
}

hydraulics.regulatedPsiXylem <- function(E, psiUpstream, kxmax, c, d, psiStep = -0.01) {
    .Call('medfate_regulatedPsiXylem', PACKAGE = 'medfate', E, psiUpstream, kxmax, c, d, psiStep)
}

hydraulics.vanGenuchtenConductance <- function(psi, ksmax, n, alpha) {
    .Call('medfate_vanGenuchtenConductance', PACKAGE = 'medfate', psi, ksmax, n, alpha)
}

hydraulics.E2psiVanGenuchten <- function(E, psiSoil, ksmax, n, alpha, psiStep = -0.01, psiMax = -10.0) {
    .Call('medfate_E2psiVanGenuchten', PACKAGE = 'medfate', E, psiSoil, ksmax, n, alpha, psiStep, psiMax)
}

hydraulics.E2psiTwoElements <- function(E, psiSoil, ksmax, kxmax, n, alpha, c, d, psiStep = -0.001, psiMax = -10.0) {
    .Call('medfate_E2psiTwoElements', PACKAGE = 'medfate', E, psiSoil, ksmax, kxmax, n, alpha, c, d, psiStep, psiMax)
}

hydraulics.supplyFunction <- function(Emax, psiSoil, ksmax, kxmax, n, alpha, c, d, dE = 0.1, psiMax = -10.0) {
    .Call('medfate_supplyFunction', PACKAGE = 'medfate', Emax, psiSoil, ksmax, kxmax, n, alpha, c, d, dE, psiMax)
}

hydraulics.regulatedPsiTwoElements <- function(Emax, psiSoil, ksmax, kxmax, n, alpha, c, d, dE = 0.1, psiMax = -10.0) {
    .Call('medfate_regulatedPsiTwoElements', PACKAGE = 'medfate', Emax, psiSoil, ksmax, kxmax, n, alpha, c, d, dE, psiMax)
}

.parcohort <- function(SP, H, CR, LAI, SpParams) {
    .Call('medfate_parcohort', PACKAGE = 'medfate', SP, H, CR, LAI, SpParams)
}

.parheight <- function(heights, SP, H, CR, LAI, SpParams) {
    .Call('medfate_parheight', PACKAGE = 'medfate', heights, SP, H, CR, LAI, SpParams)
}

.swrheight <- function(heights, SP, H, CR, LAI, SpParams) {
    .Call('medfate_swrheight', PACKAGE = 'medfate', heights, SP, H, CR, LAI, SpParams)
}

.parExtinctionProfile <- function(z, x, SpParams, gdd = NA_real_) {
    .Call('medfate_parExtinctionProfile', PACKAGE = 'medfate', z, x, SpParams, gdd)
}

.swrExtinctionProfile <- function(z, x, SpParams, gdd = NA_real_) {
    .Call('medfate_swrExtinctionProfile', PACKAGE = 'medfate', z, x, SpParams, gdd)
}

.cohortAbsorbedSWRFraction <- function(z, x, SpParams, gdd = NA_real_) {
    .Call('medfate_cohortAbsorbedSWRFraction', PACKAGE = 'medfate', z, x, SpParams, gdd)
}

.PenmanMonteithPET <- function(rc, elevation, Tmin, Tmax, RHmin, RHmax, Rn, u = NA_real_) {
    .Call('medfate_PenmanMonteithPET', PACKAGE = 'medfate', rc, elevation, Tmin, Tmax, RHmin, RHmax, Rn, u)
}

soil.theta2psi <- function(clay, sand, theta) {
    .Call('medfate_theta2psi', PACKAGE = 'medfate', clay, sand, theta)
}

soil.psi2theta <- function(clay, sand, psi) {
    .Call('medfate_psi2theta', PACKAGE = 'medfate', clay, sand, psi)
}

soil.USDAType <- function(clay, sand) {
    .Call('medfate_soilUSDAType', PACKAGE = 'medfate', clay, sand)
}

soil.vanGenuchtenParams <- function(soilType) {
    .Call('medfate_vanGenuchtenParams', PACKAGE = 'medfate', soilType)
}

soil <- function(SoilParams, W = as.numeric( c(1.0,1.0,1.0))) {
    .Call('medfate_soil', PACKAGE = 'medfate', SoilParams, W)
}

.er <- function(DOY, ERconv = 0.05, ERsyn = 0.2) {
    .Call('medfate_er', PACKAGE = 'medfate', DOY, ERconv, ERsyn)
}

.gdd <- function(DOY, Temp, Tbase = 5.0) {
    .Call('medfate_gdd', PACKAGE = 'medfate', DOY, Temp, Tbase)
}

swb.SoilEvaporation <- function(DEF, PETs, Gsoil) {
    .Call('medfate_soilevaporation', PACKAGE = 'medfate', DEF, PETs, Gsoil)
}

.infiltrationDay <- function(NetPrec, Ssoil) {
    .Call('medfate_infiltrationDay', PACKAGE = 'medfate', NetPrec, Ssoil)
}

.interceptionGashDay <- function(Precipitation, Cm, p, ER = 0.05) {
    .Call('medfate_interceptionGashDay', PACKAGE = 'medfate', Precipitation, Cm, p, ER)
}

.swbDay1 <- function(x, soil, gdd, pet, rain, er, runon = 0.0, hydraulicMode = "Simple", verbose = FALSE) {
    .Call('medfate_swbDay1', PACKAGE = 'medfate', x, soil, gdd, pet, rain, er, runon, hydraulicMode, verbose)
}

.swbDay2 <- function(x, soil, gdd, tmin, tmax, rhmin, rhmax, rad, wind, latitude, elevation, J, rain, er, runon = 0.0, hydraulicMode = "Simple") {
    .Call('medfate_swbDay2', PACKAGE = 'medfate', x, soil, gdd, tmin, tmax, rhmin, rhmax, rad, wind, latitude, elevation, J, rain, er, runon, hydraulicMode)
}

.swbgridDay <- function(lct, xList, soilList, waterO, queenNeigh, waterQ, gddVec, petVec, rainVec, erVec, trackSpecies) {
    .Call('medfate_swbgridDay', PACKAGE = 'medfate', lct, xList, soilList, waterO, queenNeigh, waterQ, gddVec, petVec, rainVec, erVec, trackSpecies)
}

swb <- function(x, soil, meteo, petMode = "Input", hydraulicMode = "Simple", latitude = NA_real_, elevation = NA_real_, verbose = TRUE) {
    .Call('medfate_swb', PACKAGE = 'medfate', x, soil, meteo, petMode, hydraulicMode, latitude, elevation, verbose)
}

.windSpeedAtCanopyHeight <- function(wind20H, canopyHeight) {
    .Call('medfate_windSpeedAtCanopyHeight', PACKAGE = 'medfate', wind20H, canopyHeight)
}

.unshelteredMidflameWindSpeed <- function(wind20H, fuelBedHeight) {
    .Call('medfate_unshelteredMidflameWindSpeed', PACKAGE = 'medfate', wind20H, fuelBedHeight)
}

.shelteredMidflameWindSpeed <- function(wind20H, crownFillProportion, topCanopyHeight) {
    .Call('medfate_shelteredMidflameWindSpeed', PACKAGE = 'medfate', wind20H, crownFillProportion, topCanopyHeight)
}

fuel.WindAdjustmentFactor <- function(topShrubHeight, bottomCanopyHeight, topCanopyHeight, canopyCover) {
    .Call('medfate_windAdjustmentFactor', PACKAGE = 'medfate', topShrubHeight, bottomCanopyHeight, topCanopyHeight, canopyCover)
}

.windSpeedAtHeightOverCanopy <- function(z, wind20H, canopyHeight) {
    .Call('medfate_windSpeedAtHeightOverCanopy', PACKAGE = 'medfate', z, wind20H, canopyHeight)
}

.windExtinctionProfile <- function(z, wind20H, LAIc, canopyHeight) {
    .Call('medfate_windExtinctionProfile', PACKAGE = 'medfate', z, wind20H, LAIc, canopyHeight)
}

